server:
  port: 9998
  servlet:
    context-path: /smart-cloud-oauth2

spring:
  application:
    # 应用名
    name: smart-cloud-oauth2
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.121:8848,192.168.2.122:8848,192.168.2.123:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 192.168.2.126
    port: 6383
    database: 0

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位秒，-1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-head: true